added mark up to component AddDrinkForm
DanyloTytarenko/DrinkMaster pull request #3
Opened 2023-10-28 10:18 UTC by sgrischenko8

2023-10-28 10:39 UTC, DanyloTytarenko commented
Use styled components instead of inline styles please

2023-10-28 10:44 UTC, DanyloTytarenko requested changes

2023-10-28 10:44 UTC, DanyloTytarenko commented on src/components/AddDrinkForm/DrinkDescriptionFields/DrinkDescriptionFields.jsx
> +            textTransform: 'capitalize',
add handler to the onChange event

2023-10-28 10:44 UTC, DanyloTytarenko commented on src/components/AddDrinkForm/DrinkDescriptionFields/DrinkDescriptionFields.jsx
> +            textTransform: 'capitalize',
Same as above

2023-10-28 16:40 UTC, sgrischenko8 commented on src/components/AddDrinkForm/DrinkDescriptionFields/DrinkDescriptionFields.jsx
> +            textTransform: 'capitalize',
added onChange function

2023-10-28 16:40 UTC, sgrischenko8 commented on src/components/AddDrinkForm/DrinkDescriptionFields/DrinkDescriptionFields.jsx
> +            textTransform: 'capitalize',
added onChange function

2023-10-29 21:00 UTC, DanyloTytarenko approved these changes

2023-10-29 21:00 UTC, merged